name = "hello-human"
license = "MIT"
licenselink = "https://github.com/invider/hugo-theme-hello-human/blob/master/LICENSE.md"
description = "Invasion Theme"
tags = ["blog", "clean", "customizable", "dark", "highlighting", "light", "minimal", "monochromatic", "multilingual", "personal", "responsive", "simple", "technical"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.30

[author]
  name = "Igor Khotin"
  homepage = "http://ikhotin.com"
  twitter = "https://twitter.com/chaostarter"

[original]
  name = "Djordje Atlialp"
  homepage = "https://atlialp.com"
  twitter = "https://twitter.com/rhazdon"
